{
  imports = [
    ../../modules/disko.nix
    ../../modules/shared.nix
  ];
  # Put your username here for login
  users.users.user.name = "root";

  # Set this for clan commands use ssh i.e. `clan machines update`
  # If you change the hostname, you need to update this line to root@<new-hostname>
  # This only works however if you have avahi running on your admin machine else use IP
  clan.core.networking.targetHost = "root@w1.zroot.org";

  # You can get your disk id by running the following command on the installer:
  # Replace <IP> with the IP of the installer printed on the screen or by running the `ip addr` command.
  # ssh root@<IP> lsblk --output NAME,ID-LINK,FSTYPE,SIZE,MOUNTPOINT
  disko.devices.disk.main.device = "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0";

  # IMPORTANT! Add your SSH key here
  # e.g. > cat ~/.ssh/id_ed25519.pub
  users.users.root.openssh.authorizedKeys.keys = [
    ''
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID2Jx9OpESota5m74e+HLilV7p/LWtIb3mhOcd3U0PYX manuel@mbp
    ''
  ];
  /*
    After jon is deployed, uncomment the following line
    This will allow sara to share the VPN overlay network with jon
    The networkId is generated by the first deployment of jon
  */
  # clan.core.networking.zerotier.networkId = builtins.readFile ../jon/facts/zerotier-network-id;
}
